name: dingtalk_suite_configurations
label: 钉钉服务商配置
fields:
  suite_ticket:
    label: suite_ticket
    type: text
    hidden: true
  suite_access_token:
    label: suite_access_token
    type: text
    hidden: true
hidden: true