name: product_amount
create: true
data_type: currency
filterable: false
generated: false
hidden: false
index: false
is_name: false
is_wide: false
label: 产品金额
multiple: false
precision: 18
primary: false
readonly: false
scale: 2
searchable: false
show_as_qr: false
sort_no: 72
sortable: false
summary_field: amount
summary_filters: []
summary_object: purchase_contract_product
summary_type: sum
type: summary
unique: false
write_requires_master_read: false
