name: product_description
create: true
filterable: false
generated: false
hidden: false
index: false
is_name: false
is_wide: false
label: 产品说明
multiple: false
primary: false
readonly: false
required: false
rows: 2
searchable: false
show_as_qr: false
sort_no: 190
sortable: false
type: textarea
unique: false
write_requires_master_read: false
