name: product_number
create: true
filterable: false
formula: 'cp-{00000}'
generated: false
hidden: false
index: false
is_name: false
is_wide: false
label: 产品编号
multiple: false
primary: false
readonly: false
searchable: false
show_as_qr: false
sort_no: 110
sortable: false
type: autonumber
unique: false
write_requires_master_read: false
