name: product_barcode
create: true
filterable: false
generated: false
hidden: false
index: false
is_name: false
is_wide: false
label: 产品条码
multiple: false
primary: false
readonly: false
required: false
searchable: false
show_as_qr: false
sort_no: 120
sortable: false
type: text
unique: false
write_requires_master_read: false
