name: product
compactLayouts:
  - product_number
  - specification
  - measurement
  - material_group
  - sales_unit
  - purchase_unit_price
  - product_description
  - product_barcode
  - tax_code
custom: true
enable_api: true
enable_dataloader: true
enable_enhanced_lookup: true
enable_events: false
enable_files: false
enable_inline_edit: true
enable_instances: false
enable_notes: false
enable_share: false
enable_tasks: false
enable_tree: false
enable_workflow: false
icon: apps
is_enable: true
is_system: true
label: 产品
version: 2
