version: "3.9"

services:

  steedos:
    image: ecr.aws.steedos.cn/dockerhub/steedos/steedos-enterprise:2.6.2-beta.24
    ports:
      - "5000:5000"
    env_file:
      - .env.local
    environment:
      - PORT=5000
      - MONGO_URL=mongodb://mongodb:27017/steedos-demo
      - MONGO_OPLOG_URL=mongodb://mongodb:27017/local
      - TRANSPORTER=redis://redis:6379
      - CACHER=redis://redis:6379/1
      - STEEDOS_STORAGE_DIR=/steedos-storage
      - STEEDOS_CRON_INSTANCERECORDQUEUE_INTERVAL=10000
      - NPM_REGISTRY_URL=https://registry.npmmirror.com
      - STEEDOS_AMIS_VERSION=3.2.0
      - STEEDOS_ENABLE_PROCESS_TRIGGER=true
      - DEVELOPER_STANDARD_OBJECTS=true
      - STEEDOS_LICENSE=6e890bc491b8c1d0edfcaa717d301478e12aa60015922ff31c55db96f74947d941a7201460baba3d9c53ffefc961a2e8e91f98db286a83f47874a004a786a40ddb52c76e6a94d328ac43fd9d338806cd5bc71ed342a90cfe42e81f557690ca653ec1d8dcb906c7e0fd344feafdf5def156242caa4f52a738d37fa52f45edfd390d3e85fb7a35d25755d980eee6164f5208a1019d616e805fad737ee9a549becd710c2e642129efd58439c90c3aa5ce3665a6503590d66505ed64b909fd95a76de9e36bf46b4ad656a896e486a773c1ea1b43108ecb5e9db77ef3a311f28753f10225cb538ba04198cbbdc74b0e5dd13ba2fe024f202d8b7d00c13d6a8363d8cc8a2bf4a79c9f8387c0ae815aa57d4df63e3194c1606df34f60abf2bdf8697da93fa27e29f1f4c193960febcf46a804ee3bbf92d98effa2e6f219e2ee503afa9dfb894aa5396a0351496a0526ec710b03bb70262123c16b23d6fa67639cd80567d1f50db0df441fa707272e6d5e4f3702b7485173702cafc81a0e2bd8aa2c9cf37ff1c3dff6738b6ed4d52b3bd24d35a9fdef2ce6109e58891e222ed712fce8b10af8883256facc8e907ba5e493b6fa47f5b00956abc53e4a63448d752bb65da619d8972a639a517b22946cf43322f3fd375d6deee8519d35265f3d9960a2668c06b5737bcc6b7b2f5a7e598ed6175a4f194637dd0c43c94a71bbe5015c8cf36c,2022-0001
      # 启用SAAS
      - STEEDOS_TENANT_ENABLE_SAAS=true
      # OpenID Connect
      - STEEDOS_IDENTITY_OIDC_ENABLED=true
      - STEEDOS_IDENTITY_OIDC_CONFIG_URL=https://id.steedos.cn/realms/master/.well-known/openid-configuration
      - STEEDOS_IDENTITY_OIDC_CLIENT_ID=steedos-oidc-public
      - STEEDOS_IDENTITY_OIDC_CLIENT_SECRET=none
      - STEEDOS_IDENTITY_OIDC_NAME=Steedos ID
      - STEEDOS_IDENTITY_OIDC_LOGO=
      - STEEDOS_IDENTITY_OIDC_REQUIRE_LOCAL_ACCOUNT=false
      # 自定义未登录时和注册后跳转的页面
      - STEEDOS_TENANT_PAGE_LOGIN=/api/global/auth/oidc/config
      - STEEDOS_TENANT_PAGE_LOGOUT=/api/global/auth/oidc/logout
    volumes:
      - "./steedos-storage:/steedos-storage"
      # - "./.steedos:/app/.steedos"
    depends_on:
      mongodb:
        condition: service_healthy
        
  redis:
    image: redis:6.2.10
    command: "redis-server --save \"\" --appendonly no --loglevel warning"
    ports:
      - "6379:6379"
  
  mongodb:
    image: mongo:4.4
    ports:
      - 27017:27017
    command: "--bind_ip_all --replSet steedos --logpath /var/log/mongodb/mongod.log"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo --quiet | grep 1
      interval: 10s
      timeout: 10s
      retries: 5
    volumes:
      - './steedos-storage-mongodb:/data/db'

  mongodb-init:
    image: mongo:4.4
    restart: "no"
    depends_on:
      mongodb:
        condition: service_healthy
    command: >
      mongo --host mongodb:27017 --eval "rs.initiate({ _id: 'steedos', members: [{_id: 0, host: 'mongodb:27017'}]})"
