version: "3.9"

services:

  steedos:
    image: ecr.aws.steedos.cn/dockerhub/steedos/steedos-enterprise:2.6.6-beta.5
    ports:
      - "5000:5000"    # Steedos
      - "27017:27017"  # MongoDB
      - "9001:9001"    # Supervisor
      - "6379:6379"    # Redis
    env_file:
      - .env
      - .env.local
    volumes:
      - "./steedos-storage:/steedos-storage"
      - "./scripts/routers:/app/node_modules/@steedos/service-ancillary/main/default/routers"
      - "../public:/app/public"
